server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: modonor
    password: modonor
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
jwt:
  secret: UnaClaveMuyLargaDe32Caracteres..
  expiration-ms: 3600000